rules:
  - DOMAIN-SUFFIX,sftcwl.com,🎯 全球直连
  - DOMAIN-SUFFIX,baidu.com,🎯 全球直连
  - DOMAIN-SUFFIX,taobao.com,🎯 全球直连
  - DOMAIN-SUFFIX,aliyun.com,🎯 全球直连
  - DOMAIN-SUFFIX,qq.com,🎯 全球直连
  - DOMAIN-SUFFIX,bilibili.com,🚀 节点选择
  - DOMAIN-SUFFIX,sf-express.com,🎯 全球直连
